USE [GamingSite]
GO

CREATE TABLE [dbo].[SYS_USER](
	[UserName] [varchar](150) NOT NULL,
	[Password] [varchar](200) NOT NULL,
	[IsAdmin] [int] NULL,
 CONSTRAINT [PK_SYS_USER] PRIMARY KEY CLUSTERED 
(
	[UserName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SYS_USER] ADD  CONSTRAINT [DF_SYS_USER_IsAdmin]  DEFAULT ((0)) FOR [IsAdmin]
GO


CREATE TABLE [dbo].[GENRE](
	[GenreId] [varchar](200) NOT NULL,
	[Description] [text] NULL,
 CONSTRAINT [PK_GENRE] PRIMARY KEY CLUSTERED 
(
	[GenreId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


CREATE TABLE [dbo].[GAME](
	[GameId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[ReleaseYear] [int] NULL,
	[Genre] [varchar](200) NULL,
	[CreationDate] [datetime] NULL,
	[ImageURL] [text] NULL,
	[GameInfo] [text] NULL,
	[Rating] [float] NULL,
 CONSTRAINT [PK_GAME] PRIMARY KEY CLUSTERED 
(
	[GameId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[GAME]  WITH CHECK ADD  CONSTRAINT [FK_GAME_GENRE] FOREIGN KEY([Genre])
REFERENCES [dbo].[GENRE] ([GenreId])
GO

ALTER TABLE [dbo].[GAME] CHECK CONSTRAINT [FK_GAME_GENRE]
GO

CREATE TABLE [dbo].[SYSTEM_REQ](
	[Processor] [varchar](200) NULL,
	[Memory] [varchar](50) NULL,
	[OS] [varchar](200) NULL,
	[Game] [int] NOT NULL,
	[SystemRequirementsId] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_SYSTEM_REQ] PRIMARY KEY CLUSTERED 
(
	[SystemRequirementsId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SYSTEM_REQ]  WITH CHECK ADD  CONSTRAINT [FK_SYSTEM_REQ_GAME] FOREIGN KEY([Game])
REFERENCES [dbo].[GAME] ([GameId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[SYSTEM_REQ] CHECK CONSTRAINT [FK_SYSTEM_REQ_GAME]
GO

CREATE TABLE [dbo].[COMMENT](
	[CommentId] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [varchar](150) NOT NULL,
	[GameId] [int] NOT NULL,
	[CommentText] [text] NULL,
 CONSTRAINT [PK_Comment] PRIMARY KEY CLUSTERED 
(
	[CommentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[COMMENT]  WITH CHECK ADD  CONSTRAINT [FK_Comment_GameId] FOREIGN KEY([GameId])
REFERENCES [dbo].[GAME] ([GameId])
GO

ALTER TABLE [dbo].[COMMENT] CHECK CONSTRAINT [FK_Comment_GameId]
GO

ALTER TABLE [dbo].[COMMENT]  WITH CHECK ADD  CONSTRAINT [FK_Comment_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[SYS_USER] ([UserName])
GO

ALTER TABLE [dbo].[COMMENT] CHECK CONSTRAINT [FK_Comment_User]
GO


CREATE TABLE [dbo].[RATING](
	[Rating] [int] NOT NULL,
	[GameId] [int] NOT NULL
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[RATING]  WITH CHECK ADD  CONSTRAINT [FK_RATING_GAME1] FOREIGN KEY([GameId])
REFERENCES [dbo].[GAME] ([GameId])
GO

ALTER TABLE [dbo].[RATING] CHECK CONSTRAINT [FK_RATING_GAME1]
GO

CREATE TABLE [dbo].[DEVELOPER](
	[GameId] [int] NULL,
	[DeveloperId] [varchar](200) NOT NULL,
 CONSTRAINT [PK_DEVELOPER_1] PRIMARY KEY CLUSTERED 
(
	[DeveloperId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[DEVELOPER]  WITH CHECK ADD  CONSTRAINT [FK_DEVELOPER_GAME1] FOREIGN KEY([GameId])
REFERENCES [dbo].[GAME] ([GameId])
GO

ALTER TABLE [dbo].[DEVELOPER] CHECK CONSTRAINT [FK_DEVELOPER_GAME1]
GO

